// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBQonE7V0pjDUKZug7sSgQJyjy-VCutHc',
    appId: '1:33969899605:web:5bd52f2bffa0052f3e2cdc',
    messagingSenderId: '33969899605',
    projectId: 'flutter-orderfood-1b333',
    authDomain: 'flutter-orderfood-1b333.firebaseapp.com',
    storageBucket: 'flutter-orderfood-1b333.firebasestorage.app',
    measurementId: 'G-4QZNFETVDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyaFFapXbKXyeFX8fpv7FH-CCWDqGKQVI',
    appId: '1:33969899605:android:11138e904a1316863e2cdc',
    messagingSenderId: '33969899605',
    projectId: 'flutter-orderfood-1b333',
    storageBucket: 'flutter-orderfood-1b333.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-aRwuQb0TODb9QHEvKMZeEQUI8Sson4o',
    appId: '1:33969899605:ios:b6125ae5a5dca6203e2cdc',
    messagingSenderId: '33969899605',
    projectId: 'flutter-orderfood-1b333',
    storageBucket: 'flutter-orderfood-1b333.firebasestorage.app',
    iosClientId:
        '33969899605-stjqatl787slve0eek9cfmqtdfmthjkb.apps.googleusercontent.com',
    iosBundleId: 'com.example.orderFoodFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-aRwuQb0TODb9QHEvKMZeEQUI8Sson4o',
    appId: '1:33969899605:ios:b6125ae5a5dca6203e2cdc',
    messagingSenderId: '33969899605',
    projectId: 'flutter-orderfood-1b333',
    storageBucket: 'flutter-orderfood-1b333.firebasestorage.app',
    iosClientId:
        '33969899605-stjqatl787slve0eek9cfmqtdfmthjkb.apps.googleusercontent.com',
    iosBundleId: 'com.example.orderFoodFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBQonE7V0pjDUKZug7sSgQJyjy-VCutHc',
    appId: '1:33969899605:web:9cb4b9a1d368400a3e2cdc',
    messagingSenderId: '33969899605',
    projectId: 'flutter-orderfood-1b333',
    authDomain: 'flutter-orderfood-1b333.firebaseapp.com',
    storageBucket: 'flutter-orderfood-1b333.firebasestorage.app',
    measurementId: 'G-KXKRRVH44C',
  );
}
