const PUBSUB_EVENT_TYPES = {
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_STATUS_UPDATED: "ORDER_STATUS_UPDATED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  ORDER_COMPLETED: "ORDER_COMPLETED",
  ORDER_DELETED: "ORDER_DELETED",
  SHIPPER_ACCEPTED_ORDER: "SHIPPER_ACCEPTED_ORDER",
  SHIPPER_STARTED_DELIVERY: "SHIPPER_STARTED_DELIVERY",
  SHIPPER_COMPLETED_DELIVERY: "SHIPPER_COMPLETED_DELIVERY",
  ML_PREDICTION_UPDATED: "ML_PREDICTION_UPDATED",
};

module.exports = PUBSUB_EVENT_TYPES;
